### ISSUE TITLE
Example using tokio-executor-trait and tokio-reactor-trait

### ISSUE THREAD

**Issue by ndelvalle** [amqp-rs/executor-trait#1]
Can you provide a pretty small example on how to use these traits directly instead of using `tokio_amqp`? 🙏🏼
And thanks for your awesome work on lapin.

**Comment by Keruspe** [comment]
Hi,

This issue probably better belongs to lapin itself.
The code in tokio-amqp is rather simple, the relevant section is right here: https://github.com/amqp-rs/lapin/blob/2.0-deprecated-integration/tokio/src/lib.rs#L28-L37

I'd be happy to accept a pull request to update the documentation in lapin to reflect this

**Comment by ndelvalle** [comment]
Thanks for pointing me to the right direction, I was able to create a `ConnectionProperties` instance with tokio executor and reactor doing:

```rust
let connection_properties = ConnectionProperties::default()
      .with_executor(tokio_executor_trait::Tokio::current())
      .with_reactor(tokio_reactor_trait::Tokio);
```

I can add an example on the lapin repo. Where should I put it? Considering that the tokio folder does not exist anymore? 
I was thinking maybe in
* https://github.com/amqp-rs/lapin/tree/main/examples
* https://github.com/amqp-rs/lapin/blob/main/src/connection_properties.rs as an example

**Comment by Keruspe** [comment]
I guess an example would be ok. Thanks!
